apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: url-shortener
  labels:
    app: url-shortener
    component: postgres
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: url-shortener
    component: postgres
